### ISSUE TITLE
Failed at `npm start`

### ISSUE THREAD

**Issue by jasonlam-swatow** [xpepermint/vue-example#2]
npm: v3.10.10
node: v5.4.0

Ran `npm start` after install all dependencies, error logged as:

```
> vue-example@1.20.2 start /Users/mac/vue-example
> node --harmony --icu-data-dir=node_modules/icu4c-data ./scripts/start

/Users/mac/vue-example/scripts/start.js:1
(function (exports, require, module, __filename, __dirname) { const {Server} = require('..');
                                                                    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:1003:3

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.4.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vue-example@1.20.2 start: `node --harmony --icu-data-dir=node_modules/icu4c-data ./scripts/start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-example@1.20.2 start script 'node --harmony --icu-data-dir=node_modules/icu4c-data ./scripts/start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --harmony --icu-data-dir=node_modules/icu4c-data ./scripts/start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mac/vue-example/npm-debug.log
```

**Comment by xpepermint** [comment]
Try using the latest `node` version.

From the readme: `This project is based on vue-clie-template and requires Node.js v7+.`

**Comment by xpepermint** [comment]
Closing this issue. Please reopen it if my answer above doesn't solve your problem.
