### ISSUE TITLE
bug in running

### ISSUE THREAD

**Issue by brw31415** [xpepermint/vue-example#3]
hi, 
the install seemed to work:

$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN vue-example@1.21.1 No repository field.

Ubuntu 14.

node v6.11.2

$ npm start

> vue-example@1.21.1 start /home/ubuntu/workspace/vue-example
> node --harmony --icu-data-dir=node_modules/icu4c-data ./scripts/start

/home/ubuntu/workspace/vue-example/src/server/index.js:24
  async listen () {
        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/workspace/vue-example/src/index.js:1:80)
    at Module._compile (module.js:570:32)

npm ERR! Linux 4.9.17-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/node" "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/npm" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vue-example@1.21.1 start: `node --harmony --icu-data-dir=node_modules/icu4c-data ./scripts/start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-example@1.21.1 start script 'node --harmony --icu-data-dir=node_modules/icu4c-data ./scripts/start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --harmony --icu-data-dir=node_modules/icu4c-data ./scripts/start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/vue-example/npm-debug.log

**Comment by xpepermint** [comment]
Try upgrading your node version first.

**Comment by larrysharpe** [comment]
I'm having an issue in running NPM START, with node version 8.7.0
![image](https://user-images.githubusercontent.com/5643060/31587111-ab67978e-b1a9-11e7-8a56-e40e1a435a93.png)
